# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ccp_RclT3VJMCslrQ5-RahTWTxRHmN2I
"""

import streamlit as st
import sqlite3
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt

# Load data from SQLite database
@st.cache_data
def load_data():
    conn = sqlite3.connect("ab_test.db")
    df = pd.read_sql("SELECT * FROM ab_test_results", conn)
    conn.close()
    return df

# A/B Testing function
def perform_ab_test(df):
    group_a = df[df['group'] == 'A']['conversion']
    group_b = df[df['group'] == 'B']['conversion']

    conversion_rate_a = group_a.mean()
    conversion_rate_b = group_b.mean()
    t_stat, p_value = stats.ttest_ind(group_a, group_b)

    return conversion_rate_a, conversion_rate_b, t_stat, p_value

# Streamlit UI
st.title(" A/B Testing Dashboard")
df = load_data()

st.write("### Raw Data Preview", df.head())

conversion_rate_a, conversion_rate_b, t_stat, p_value = perform_ab_test(df)

st.write(f"**Conversion Rate (Group A):** {conversion_rate_a:.2%}")
st.write(f"**Conversion Rate (Group B):** {conversion_rate_b:.2%}")
st.write(f"**T-statistic:** {t_stat:.4f}")
st.write(f"**P-value:** {p_value:.4f}")

# Significance interpretation
if p_value < 0.05:
    st.success("Statistically significant difference found between Group A and B.")
else:
    st.info(" No statistically significant difference found.")

# Visualization
fig, ax = plt.subplots()
df.groupby('group')['conversion'].mean().plot(kind='bar', ax=ax)
ax.set_ylabel("Conversion Rate")
ax.set_title("Conversion Rate by Group")
st.pyplot(fig)
